---
apiVersion: punchline.punchplatform.io/v2
kind: SparkPunchline
metadata:
  name: punchline-notebook
spec:
  containers:
    serviceAccount: admin-user
    applicationContainer:
      image: ghcr.io/punchplatform/punchline-pyspark:8.0-dev
      imagePullPolicy: IfNotPresent
    resourcesInitContainer:
      image: ghcr.io/punchplatform/resourcectl:8.0-dev
      resourcesProviderUrl: http://artifacts-server.punch-artifacts:4245
  dependencies:
    - additional-pex:demo:dependencies:1.0.0
    - model:demo:credit_card:1.0.0
    - file:demo:credit_card_notebook:1.0.0
  engineSettings:
    spark.hadoop.fs.s3a.access.key: "minio"
    spark.hadoop.fs.s3a.aws.credentials.provider: "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    spark.hadoop.fs.s3a.endpoint: "http://minio.object-store:9002"
    spark.hadoop.fs.s3a.path.style.access: "True"
    spark.hadoop.fs.s3a.secret.key: "password"
    spark.executor.instances: "3"
  dag:
    - id: source_1
      kind: source
      type: elasticsearch
      settings:
        http_hosts:
        - host: punchplatform-es-default.doc-store
          port: 9200
          scheme: http
        index: credit_card
        security:
          credentials:
            password: elastic
            username: elastic
      out:
        - id: notebook
          table: table

    - id: notebook
      kind: function
      type: notebook
      settings:
        notebook: demo:credit_card_notebook:1.0.0
        inputs:
          - from: source_1_table
            to: data
        outputs:
          - from: everything
            to: table_1
        parameters:
          nb_rows:  5000
      out:
        - id: sink_1
          table: table_1

    - id: sink_1
      kind: sink
      type: elasticsearch
      settings:
        http_hosts:
        - host: punchplatform-es-default.doc-store
          port: 9200
          scheme: http
        index:
          type: constant
          value: credit_card_results
        security:
          credentials:
            password: elastic
            username: elastic

